### ISSUE TITLE
Error: "Cannot understand GT field."

### ISSUE THREAD

**Issue by lt11** [gkanogiannis/fastreeR#2]
Dear developer,

While I was running the following line:
```
vcf2dist(pathNucSnps, outputFile = "~/Desktop/test.txt",
         threads = 2, ignoreMissing = F, 
         onlyHets = F, ignoreHets = F, compress = F)
```
I got the following error:
```
VCF2DIST : Wed Nov 02 05:30:00 CET 2022
cpus=8
using=2
2023/08/23 16:11:06 VCFManager: START READ
16777216
Cannot understand GT field.
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  Java called System.exit(0) requesting R to quit - trying to recover
Calls: vcf2dist -> <Anonymous> -> .jrcall -> .jcall
Execution halted
```
Yet, the vcf file seems properly formatted (you can find a sample attached).

Do you have suggestion?

Thanks for your help.

Best regards,

Lorenzo

[sample-vcf.txt](https://github.com/gkanogiannis/fastreeR/files/12420331/sample-vcf.txt)

**Comment by lt11** [comment]
I think the problem may be due to ploidy. Probably fastreeR acccepts only diploid samples (while my input is from haploid samples). Is it correct?

In that case, I guess a quick-and-dirty solution could be to transform the haploid genotypes (e.g. GT = 1) into homozygous genotypes (i.e. 1/1).

**Comment by gkanogiannis** [comment]
Hi Lorenzo,

You are correct, fastreeR accepts vcf for diploid (and polyploid) genotypes.
Unfortunately, the haploid case was out of scope and was not implemented.

Fast solution is, as you already mentioned, to convert haploid genotypes to homozygous diploid genotypes.
Otherwise, give me a couple of days to implement for the haploid case as well and then you can use the development version, until it is pushed to the next Bioconductor version.

Best regards,

Anestis

**Comment by lt11** [comment]
Hi Anestis,

Thanks for the prompt reply. Please, ping me when I can download the new development version.

Best,

L

**Comment by gkanogiannis** [comment]
Hi Lorenzo,

Can you please give a try to the dev version from github and let me know? Supposedly, I added support for haploid GT codes :)

devtools::install_github("gkanogiannis/fastreeR")

Best,

Anestis

**Comment by lt11** [comment]
Hi Anestis,

Thanks a lot. Rapid and effective! It is running.

Cheers,

L
